### PR TITLE
Ipython verbosity

### PR DESCRIPTION
**Pull request by vals**
I added code similar to VerboseOptimization so the optimization looks a bit nicer in IPython notebooks when performing many iterations with verbose option.

### CODE REVIEW

**Comment by lawrennd** [comment]
Thanks for this!

For expediency, since the code's not in the core sections, just display, I'll merge now but it would be great if @jameshensman and/or @mzwiessele have time to also take a look.

Is the try, except on the second pull to check for presence of the notebook through the import? Would it make sense just to make sure the except was for the import error? I'm just asking because I've had difficult to trace bugs from try, excepts like that in the past. Although I freely admit I don't know what python 'best practice' is considered to be for this case (it may well have been done in the same way in GPy).

**Comment by vals** [comment]
To be honest I'm not sure why the second try-except is needed. (Meaning the one changing HTML properties of widgets). It's how it is done in the GPy VerboseOptimization class: https://github.com/SheffieldML/GPy/blob/c7a25f8ed1b51068ec13da1aa6fa4808dcc70661/GPy/core/verbose_optimization.py#L49 . I could imagine this being due to the IPython notebook HTML changing across versions and this keeps things stable.

The first one that checks for IPython would indeed be more clear with `except ImportError`. This is also how it is in GPy.

**Comment by lawrennd** [comment]
@mzwiessele?

On Fri, Mar 4, 2016 at 9:13 AM, Valentine Svensson <notifications@github.com

**Comment by mzwiessele** [comment]
@vals  Absolutely right, stability issues, I think the try block with the HTML changing is never successful these days and fails all the time... IPython is changing too fast and with too high of changes in the widgets that I gave up following all the changes and just put in the try block. We now also _require_ ipywidgets as it is more stable.

**Pull request merged**
